version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: cookbook_website
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10

  # backend:
  #   build: ./cookbook-backend
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cookbook_website
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: root1234

  # frontend:
  #   build: ./cookbook-frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  mysql_data:
